### ISSUE TITLE
App Install Banner issue

### ISSUE THREAD

**Issue by umaar** [GoogleChrome/samples#134]
I've launched the [app install banner sample pages](https://github.com/GoogleChrome/samples/tree/gh-pages/app-install-banner) on Chrome for Android 44.0.2 (tried the latest Dev + Beta builds from the Play store). After enabling `chrome://flags/#bypass-app-banner-engagement-checks` and relaunching Chrome, I still don't see any banner.

Any ideas? Note: I'm not signed into Chrome, is this a requirement?

/cc @PaulKinlan

**Comment by PaulKinlan** [comment]
Make sure the url is https on https://googlechrome.github.io/

**Comment by umaar** [comment]
Https is on.

Make sure the url is https on https://googlechrome.github.io/

**Comment by PaulKinlan** [comment]
Plug in devtools on Beta and see what the error is, it's imposible for me to tell otherwise.  For example, you could already have the app installed.

**Comment by umaar** [comment]
Oops didn't realise it was the I/O app, I see the banner now after uninstalling. Thanks!
