### ISSUE TITLE
Bug: push-messaging-and-notifications doesn't work on hard reload

### ISSUE THREAD

**Issue by larrykluger** [GoogleChrome/samples#135]
In file samples/push-messaging-and-notifications/main.js 
Line 174: `navigator.serviceWorker.ready.then(function(serviceWorkerRegistration) {`
#### Problem:

serviceWorker is never ready if you do a "hard reload" (shift-reload icon) or "empty cache and hard reload"
Chrome version  44.0.2403.39 beta-m (64-bit)

Test: try it at https://widgetsign.com/chrome_samples/push-messaging-and-notifications/
Fault: the button is never enabled if you do a shift-reload.

**Comment by addyosmani** [comment]
@gauntface if you get a chance, could you PTAL?

**Comment by gauntface** [comment]
I believe this is a bug with Chrome, I've re-nudged the bug - https://code.google.com/p/chromium/issues/detail?id=462529
