### ISSUE TITLE
Use eslint to standardize on JS code style

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/samples#141]
It's been suggested in the past (by @gauntface I believe) to include a top-level [`jscs`](http://jscs.info/) configuration in this repo. It might be difficult to automatically enforce the styles, but including a reference that folks could opt into would do some good.

**Comment by addyosmani** [comment]
:+1:

**Comment by jeffposnick** [comment]
`jscs` doesn't currently support extracting JS `<script>` blocks from HTML files (at least not until [this PR](https://github.com/jscs-dev/node-jscs/pull/1038) is merged).

`jshint` appears to do a decent job of extracting out JS `<script>` tags, though. While `jshint`'s focus is slightly different that `jscs`'s, it's still useful, and I'm going to look into use it instead.

**Comment by jeffposnick** [comment]
I think this can be handled by moving to `eslint` with a standard config.

**Comment by gauntface** [comment]
Now that everything is getting externalised I think we could do this fairly
soon when PRs calm down for templatizing.

**Comment by jeffposnick** [comment]
Yup, though since it makes sense to use `eslint` for code style, we'll need a reference set of rules to use as a base. I believe @addyosmani is looking into that.
