### ISSUE TITLE
generators directory should have es-6 on the end of the directory name

### ISSUE THREAD

**Issue by PaulKinlan** [GoogleChrome/samples#143]
https://github.com/GoogleChrome/samples/tree/gh-pages/generators a lot of the other es-6 feature end in es-6.

cc @jeffposnick

**Comment by spiralx** [comment]
That's also the case for

https://github.com/GoogleChrome/samples/tree/gh-pages/spread-operator

and I think

https://github.com/GoogleChrome/samples/tree/gh-pages/encoding-api
https://github.com/GoogleChrome/samples/tree/gh-pages/extended-unicode-escapes

**Comment by jeffposnick** [comment]
Closing out this old issue as:
- I'm nervous about breaking existing URLs by renaming directories.
- The "JavaScript" tab of the new https://www.chromestatus.com/samples surfaces all our samples related to new JavaScript functionality, without relying on directory naming conventions.

That being said, we'll shoot for the `-es6` or `-es7` suffix when appropriate moving forward.
