### ISSUE TITLE
ES6 TypedArray methods sample

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/samples#145]
See https://www.chromestatus.com/feature/4919908559224832

**Comment by jeffposnick** [comment]
This seems closely related to https://github.com/GoogleChrome/samples/issues/144. Can I add you as the owner of this one too, @beaufortfrancois? You can probably roll them up into a single page.

**Comment by beaufortfrancois** [comment]
I've assigned myself and will wait for #144 review if that's OK.

**Comment by addyosmani** [comment]
https://github.com/GoogleChrome/samples/pull/163 has now landed

**Comment by beaufortfrancois** [comment]
Will do that this morning.

**Comment by beaufortfrancois** [comment]
Done.
