### ISSUE TITLE
Rest parameters (ES6) sample

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/samples#146]
See https://www.chromestatus.com/feature/5937087912083456

**Comment by addyosmani** [comment]
We'll be shipping this feature as part of M47 and it'll be mentioned in the Chromium blog post. Re-assigning my way to get the sample done.

**Comment by jeffposnick** [comment]
https://github.com/GoogleChrome/samples/tree/gh-pages/rest-parameters-es6
