### ISSUE TITLE
Spread (call and array) (ES6) sample

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/samples#147]
See https://www.chromestatus.com/feature/6031334694715392

**Comment by addyosmani** [comment]
@surma worked on https://github.com/GoogleChrome/samples/pull/116. We should check if there's anything else we want to tackle there and if the sample requires updating.

**Comment by addyosmani** [comment]
We've had to unship Spread as well for this release. Let's focus on the other samples.

**Comment by jeffposnick** [comment]
This was added after the fact: https://github.com/GoogleChrome/samples/tree/gh-pages/spread-operator
