### ISSUE TITLE
Touch.rotationAngle sample

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/samples#149]
See https://www.chromestatus.com/feature/4639728380936192

**Comment by jeffposnick** [comment]
@rbyers has an extensive demo at http://rbyers.github.io/paint.html and I think we'd be fine just directing developers to that.

**Comment by PaulKinlan** [comment]
How do they see the code easily?  I am still in two minds about not have a central set of samples.

**Comment by jeffposnick** [comment]
For browsing, the yet-to-be-built https://chromestatus.com/samples landing page will list `Touch.rotationAngle` and links to whatever URL we have associated with that feature entry. Most cases it would be a URL belonging to our repo, but in this case it's a URL pointing elsewhere.

For searching, Googling "Touch.rotationAngle" leads to MDN first and then https://www.chromestatus.com/feature/4639728380936192. That landing page has a prominent link to the sample.

**Comment by PaulKinlan** [comment]
The problem with Rick's Sample is that it is demonstrates many things all at once and it is nearly impossible to find the source of it.

**Comment by PaulKinlan** [comment]
I have an isolated sample for this.

**Comment by RByers** [comment]
FWIW I agree - paint.html was intended as a demo, not a code sample.
