### ISSUE TITLE
Externalize JS (and CSS?) files

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/samples#207]
Moving the discussion from https://github.com/GoogleChrome/samples/pull/206

The benefits would be that it's generally a best practice, and it would make it easier to run `ESLint` and `JSCS` against the `.js` files directly, without having to extract them from the generated HTML. Now that we're on a Jekyll build for the site, we have a lot more flexibility.

The drawbacks would be that the View Source... experience is arguably worse for developers who want to learn about new features in context, since they'd have to match up what's going on with an external JavaScript file with the rest of the content on the main page.

The drawback might be mitigated by inlining the entire external `.js` file's source on the main page wrapped in a `<div class="hightlight">`, like we're currently doing for explicitly tagged snippets of the inline JavaScript source.

There's also the topic of whether we should do the same for CSS files. There are a handful of samples out there just demonstrate CSS functionality.

**Comment by gauntface** [comment]
We could also mitigate some of the issues by adding a link to view the source on github (which perhaps we should be doing anyway?

**Comment by jeffposnick** [comment]
There's both a "View Source" and "View on GitHub" link at the top of the currently deployed template. E.g. https://googlechrome.github.io/samples/css-motion-path/

Only a fraction of the total samples are using the templates, though. Getting more of the legacy samples moved over to the templates is another task :smile:

**Comment by gauntface** [comment]
Looking at the sample @jeffposnick has a PR for on CSS intrinsic Sizing, I'm thinking we should externalise CSS as well and then find a consistent way to inline and highlight the samples in the jekyll build.

At the moment the Raw source for the samples are getting confusing.

**Comment by gauntface** [comment]
I was just having a look into a possible way of doing this without making things too complex to handle.

I just had a stab at the allow-popups-to-escape and array-methods-es6 samples. 

What you can do is use include_relative to reference a file in the current directory which enables us to inline a file like so:

```
{% include html_snippet.html snippetFilename='demo.html' title='' %}
```

I just followed the same format in the html_snippet include but replaced printing of the captured variable with include_relative

```
{% if include.snippetFilename %}
  {% include_relative {{include.snippetFilename}} %}

  {% if include.title == null %}
    <h3>HTML Snippet</h3>
  {% elsif include.title != "" %}
    <h3>{{ include.title }}</h3>
  {% endif %}

  {% highlight html %}
  {% include_relative {{include.snippetFilename}} %}
  {% endhighlight %}
{% endif %}
```

This format would work for externalising any file.

The extra win with this is that we can inline CSS and JS as well in the final Jekyll build, meaning this won't ruin the view source aspect of the demos.

The major down side is that for demo's like array-methods-es6, you would have to create a file for each demo. I personally see this as a small price to pay considering it reduces the demos to their smallest components and is easier for people to view in github and PR in fixes compared to the inline capturing approach.

@jeffposnick what do you think?

See demo in the file-extraction branch on my fork: https://github.com/gauntface/samples/tree/file-extraction

**Comment by jeffposnick** [comment]
That looks great to me, @gauntface. And then the plan would be to just lint the underlying source files instead of `_site/`?

I don't think the number of individual files used for the `array-methods-es6` sample is typical. At least not based on the way I've structured the samples I put together.

**Comment by jeffposnick** [comment]
Closed by https://github.com/GoogleChrome/samples/pull/225
