### ISSUE TITLE
GCM Message Failing in Push Example Failing to Reach the Service Worker

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/samples#211]
This sample: https://github.com/GoogleChrome/samples/tree/gh-pages/push-messaging-and-notifications

I've double-checked this.

I've added -v to the curl command and confirmed that GCM is returning 200 OK. I've put a break point in the first line of onpush and confirmed that it's never reached.

**Comment by jeffposnick** [comment]
I just went through the full steps of registering an API key, configuring the local copy of the sample, etc. The `curl` step did trigger the notification for me, so I can't reproduce what you're seeing:

![image](https://cloud.githubusercontent.com/assets/1749548/10062586/0a53cdea-6232-11e5-90be-66c6c5c4f4b3.png)

CC: @gauntface in any case, but it does look like the code can work given the proper configuration. Can you double-check your API key in `config.json`, API project number in the `manifest.json`, etc.?

**Comment by gauntface** [comment]
@jpmedley How long did you wait from subscribing for push and receiving the push message?

Also what version of Chrome is this on?

**Comment by jpmedley** [comment]
Version:
Google Chrome   45.0.2454.99 (Official Build) (64-bit)
Revision    8813113675a50e4f7e90fec49a3eb1796454618b-refs/branch-heads/2454@{#492}
OS  Mac OS X 
Blink   537.36 (@202530)
JavaScript  V8 4.5.103.34
Flash   19.0.0.185

When I run curl, sometimes I get this back:
<HTML>
<HEAD>
<TITLE>Unauthorized</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">

<H1>Unauthorized</H1>

<H2>Error 401</H2>

</BODY>
</HTML>

Sometimes this:
{"multicast_id":7341722821521375837,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1443051876229708%2b9bbb26f9fd7ecd"}]}

In no case do I get message.

(Incidentally, If I'd gotten these two days ago, I would've suspected a GCM problem and never filed the ticket.)

**Comment by jpmedley** [comment]
@jeffposnic I triple-checked the key and number. I even generated a new key and triple-checked that.

@gauntface I'm not sure what you mean by 'how long did I wait'. Shouldn't it work immediately? It did when I used this demo last spring.

**Comment by jeffposnick** [comment]
@jpmedley is this still an issue for you? If so, maybe we should debug things over a screen sharing session. I'm hopeful that it's not a widespread issue with the sample.

**Comment by jpmedley** [comment]
I've added retesting to my to-do list.

Joe Medley | Technical Writer, DevPlat | jmedley@google.com | 816-678-7195

**Comment by jeffposnick** [comment]
After running though this with @jpmedley, we've come to the conclusion that it's something odd about his Chrome settings, rather than an issue with the code. He's able to use the code successfully when testing with a Chrome Canary instance, which has its own separate settings.
