### ISSUE TITLE
Custom offline page service worker sample shows offline page when receiving redirects in Chrome for Android 45

### ISSUE THREAD

**Issue by patternseek** [GoogleChrome/samples#213]
Hi,

The sample custom offline page sample at https://github.com/GoogleChrome/samples/tree/gh-pages/service-worker/custom-offline-page shows the offline page when the server returns a 30x redirect in Chrome for Android 45.

Thanks.

**Comment by patternseek** [comment]
My bad, the server was redirecting to HTTP rather than HTTPS. That's normally then bounced back to HTTPS.

**Comment by rios1223** [comment]
Helping me with my bug please
