### ISSUE TITLE
Add a canonical URL for each sample

### ISSUE THREAD

**Issue by beaufortfrancois** [GoogleChrome/samples#221]
It would be great to link to all demos from a canonical URL sample.

**Comment by jeffposnick** [comment]
Right now the _de facto_ canonical URL is `https://googlechrome.github.io/samples/<sample-name>`

I think I'm missing something about your suggestion. Could you elaborate?

**Comment by beaufortfrancois** [comment]
For instance Bluetooth demo/samples can be found at https://www.chromestatus.com/samples#bluetooth not only https://googlechrome.github.io/samples/web-bluetooth/

**Comment by jeffposnick** [comment]
I think I'm still missing something here. But if there's a quick PR that you want to put together to address this, I'm happy to review.

**Comment by beaufortfrancois** [comment]
Something as simple as https://github.com/GoogleChrome/chromium-dashboard/pull/245 would work. What do you think?

![screenshot 2015-10-13 at 11 35 38 am](https://cloud.githubusercontent.com/assets/634478/10451136/a0b22c5c-719e-11e5-81ab-898d1099273d.png)

![screenshot 2015-10-13 at 11 36 33 am](https://cloud.githubusercontent.com/assets/634478/10451142/aef53516-719e-11e5-93d6-1c4ccab38ccb.png)

**Comment by jeffposnick** [comment]
So maybe this is why I'm confused—you're proposing making a change in the `GoogleChrome/chromium-dashboard` project, but this is the `GoogleChrome/samples` issue tracker. Do you want to move the discussion to a new issue in `GoogleChrome/chromium-dashboard` and let @ebidel weigh in?

**Comment by beaufortfrancois** [comment]
I will. Thanks @jeffposnick!
