### ISSUE TITLE
Sample for Web Application Manifest

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/samples#24]
This is a placeholder issue for us to write a sample for the Web App Manifest demonstrating usage. Mounir recently landed this. Although not yet in a public build, Chrome Android will use the Web Manifest for the "Add  to homescreen" feature.

Spec: http://w3c.github.io/manifest/ 

Rough samples:

manifest.json

```
{
  "name": "2048 app",
  "icons": [{
        "src": "icon/lowres",
        "sizes": "64x64",
        "type": "image/webp"
      }, {
        "src": "icon/hd_small",
        "sizes": "64x64"
      }, {
        "src": "icon/hd_hi",
        "sizes": "128x128",
        "density": "2"
      }],
  "start_url": "/index.html",
  "display": "fullscreen",
  "orientation": "landscape"
}
```

index.html

```
<!doctype>
<html>
<title>My app</title>

<!-- Startup configuration -->
<link rel="manifest" href="manifest.json">
```

Intent to Ship:
https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/EbAMnvBUU80

Commits:

https://chromium.googlesource.com/chromium/src/+/b225ae560fea0648b61fad36b5972221a7f5c47d
https://chromium.googlesource.com/chromium/src/+/f60720832599bc7306d9e37e3cef5ceee4c224ce
https://chromium.googlesource.com/chromium/src/+/96297a73c48ff299e45eac62b967a8e333569602
https://chromium.googlesource.com/chromium/src/+/9317a291b84457b9a8feb8ecd94d0593bb0fff9b

**Comment by addyosmani** [comment]
@jeffposnick I think this one can be closed.

**Comment by jeffposnick** [comment]
Indeed. Thanks for filing this initially.
