### ISSUE TITLE
Error in code of example: rest parameters es6

### ISSUE THREAD

**Issue by netsi1964** [GoogleChrome/samples#252]
I saw a small error in the example code here: [rest parameters es6](https://googlechrome.github.io/samples/rest-parameters-es6/index.html)

The code says:

```
/*
We could alternatively have used Array.from here:

function sortArguments() {
  return Array.from(arguments).sort();
};
 */
```

That however is not correct, it should be:

```
function sortArguments() {
  return Array.from(arguments)[0].sort();
};
```

**Comment by beaufortfrancois** [comment]
In Chrome 48.0.2561.0, this raises `Uncaught TypeError: Array.from(...)[0].sort is not a function(…)`

**Comment by netsi1964** [comment]
You are right @beaufortfrancois - me bad :-) I will close this issue, thanks.
