### ISSUE TITLE
"View Source" link (in Fallback Response Sample) doesn't work in Firefox

### ISSUE THREAD

**Issue by marco-c** [GoogleChrome/samples#294]
Security Error: Content at https://googlechrome.github.io/samples/service-worker/fallback-response/index.html may not load or link to view-source:https://googlechrome.github.io/samples/service-worker/fallback-response/.

**Comment by jeffposnick** [comment]
I just tried this, and it's working fine for me in Firefox 45:
![image](https://cloud.githubusercontent.com/assets/1749548/13747030/b2b1cdb2-e9cc-11e5-8769-6358b90b8637.png)
Please reopen if you can still reproduce and we'll investigate further.

**Comment by marco-c** [comment]
I can reproduce in Firefox Developer Edition. I'll try to find a regression range in Firefox.

**Comment by marco-c** [comment]
Looks like it's on purpose:
https://bugzilla.mozilla.org/show_bug.cgi?id=1172165
https://developer.mozilla.org/en-US/Firefox/Releases/47#Security
https://www.fxsitecompat.com/en-CA/docs/2016/view-source-urls-can-no-longer-be-linked-from-web-pages/

P.S.: I don't have privileges to reopen the issue.

**Comment by jeffposnick** [comment]
Hmm. I haven't heard anything about similar changes coming to Chrome, but if it gets to the point where no browsers can link to `view-source:`, I'd obviously remove the link from the template.

In the meantime, though, I'm inclined to keep it in.

**Comment by marco-c** [comment]
@jeffposnick Chrome might be the only one still supporting it, according to [this Wikipedia page](https://en.wikipedia.org/wiki/View-source_URI_scheme#Browser_support).

Maybe you could remove the URL if you detect the browser isn't Chrome?

**Comment by addyosmani** [comment]
It's unfortunate that we would have to sniff for this, but I've heard Chrome may consider switching to just displaying view source items in Sources and drop this too. I'm in favor of this working cross-browser until we get consistent here. Jeff's got the final call.
