### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/samples#307]
Can we add links from the sample READMEs to the live demo?

**Comment by addyosmani** [comment]
I was under the impression we already did this: https://github.com/GoogleChrome/samples/blob/gh-pages/array-includes-es7/README.md

Are there samples missing the live links?

**Comment by jeffposnick** [comment]
Yup; it's not _enforced_, but the [starter template `README.md`](https://github.com/GoogleChrome/samples/blob/gh-pages/SAMPLE_STARTING_POINT/README.md) includes a link with placeholders that can be replaced with the actual URLs.
