### ISSUE TITLE
Android device not discoverable from Chrome Bluetooth API

### ISSUE THREAD

**Issue by mulderp** [GoogleChrome/samples#311]
Hi,

I try to discover an Android phone with the Bluetooth API via `navigator.bluetooth.requestDevice(...)`

But I don't see any device appearing. I tried different filters, device name and device prefix here: https://googlechrome.github.io/samples/web-bluetooth/device-info.html

When I use the Google Chrome Plugin BLE scanner, I can find the Android phone.

Thanks!

**Comment by beaufortfrancois** [comment]
Hello Patrick, 
Which platform do you use?

The Web Bluetooth API is supported in Chrome OS and Chrome for Android M for now.
See https://github.com/WebBluetoothCG/web-bluetooth/blob/gh-pages/implementation-status.md for more details.

**Comment by mulderp** [comment]
The device is a Motorola Moto G (2nd generation) with Android 5.0.2

More searching yesterday resulted into missing advertising support of that device. So, that might be the reason why Chrome on my desktop was not able to see the device.

Yet, the "filters" parameters in the Chrome demo is a bit confusing, e.g. what to put if I want to detect proximity of a phone? I wanted to try basically this example: in the browser https://tessel.hackster.io/ifoundthemeaningoflife/ble-proximity-switch-f5df21 

I have other BLE devices (e.g. a RedBear Labs Duo board). But maybe you have a pointer to some other way how to easily detect proximity of a device in the browser?

**Comment by mulderp** [comment]
Ok, seems the devices that support the proximity demo should be in this list below: https://github.com/WebBluetoothCG/ble-test-peripheral-android
