### ISSUE TITLE
SW Sample: Caching of Selective Resources

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/samples#32]
It should demonstrate basic registration, and then an `onfetch` handler that selectively caches responses based on multiple criteria:
- Request URL pattern (e.g. only cache URLs hosted on `example.com`)
- Response MIME type (e.g. only cache `image/*` resposnes). Subsequent requests for the same URL are served from the cache.
- Any other ideas?

Until the native Caches API is available, it should use https://github.com/coonsta/cache-polyfill

**Comment by gauntface** [comment]
- Check the response code is 200.
- Cache Google Fonts.
- Only cache resources requested from pages that we have cached during the install step.
