### ISSUE TITLE
Git fetch/push are sloooooooooow

### ISSUE THREAD

**Issue by beaufortfrancois** [GoogleChrome/samples#344]
Since `service-worker/prefetch-video/static/gbike.webm` and `service-worker/prefetch-video/static/gbike.mp4` large bin files have been added, it is so slow to run git fetch/push...
@jeffposnick Can we do something about this?

**Comment by jeffposnick** [comment]
Adding @samdutton in case he can either cut down on the video quality or length while getting his point across. I'm pretty sure that the need to be hosted locally since the responses are stored in the `Cache Storage API` as same-origin resources.

**Comment by samdutton** [comment]
Tricky. I wanted to use a longer video to show multiple range requests (partials) in action — and I've used pretty much the lowest possible quality and resolution. 

I originally used a smaller video (the one from [simpl.info/v](https://simpl.info/video), 1.9MB), but that gets downloaded in one chunk.

Can we use [Large File Storage](https://git-lfs.github.com/)? Not sure that's relevant (or will work) in this case.

Do the videos definitely need to be stored on the same domain?

If need be, I can go back to the smaller video and just use the WebM version.

**Comment by jeffposnick** [comment]
I'm about 99% sure that what you're doing with the cached `Response` objects (cutting them up when there's a `Range` header) requires either same-origin or CORS to be enabled on a remote origin. Maybe something like Google Cloud Storage could be CORS-enabled, but then you'd have the overhead of maintaining a GCS bucket.

**Comment by samdutton** [comment]
Do we have an existing GCS bucket we could use? [Buckets can be CORS-enabled](https://cloud.google.com/storage/docs/cross-origin#How_CORS_Works).

If not, I'll set one up and try it out.

**Comment by jeffposnick** [comment]
Not as far as I know. (If we did have one, @crhym3 would probably be the one who knew.)

**Comment by samdutton** [comment]
Talked to @crhym3 — will sort on Monday.

**Comment by beaufortfrancois** [comment]
Thank you!

**Comment by samdutton** [comment]
I had some problems with this, but I _think_ that was because the Request mode in the Service Worker was set to 'no-cors'.

Whatever — I changed that to 'cors' (default anyway?) and it seems to work now :). 

[samdutton.github.io/samples/service-worker/prefetch-video](https://samdutton.github.io/samples/service-worker/prefetch-video)

**Comment by addyosmani** [comment]
Can this issue be closed or is there still work being done on it?

**Comment by samdutton** [comment]
Hi @addyosmani — yes, this is fixed and can be closed.
