### ISSUE TITLE
SW Sample: Using PostMessage

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/samples#36]
It should demonstrate basic registration, and then have the client page send specific requests to the SW script via `postMessage()` on the client page/the `onmessage` handler in the SW script.

For the purposes of this example they could be simple strings that are echoed back, but in the real world a useful case would be to send a request from the client page to the SW to cache a URL or to update some sort of SW configuration.

**Comment by TalAter** [comment]
See #94

**Comment by jeffposnick** [comment]
https://googlechrome.github.io/samples/service-worker/post-message/index.html
