### ISSUE TITLE
googlechrome.github.io needs landing page

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/samples#37]
That lists all the samples.

**Comment by gauntface** [comment]
+1 this.

Maybe we could list samples and their relative chrome status page as well.

**Comment by jeffposnick** [comment]
@gauntface, if you've got the interest to take this on either here or over at https://github.com/GoogleChrome/chromium-dashboard, I think that strictly speaking, anything would be better than the nothing that we currently have. I don't believe anyone else is currently looking into this.

**Comment by PaulKinlan** [comment]
I played with it a while ago but we needed to integrate Jekyll more. If
someone is up for you will get much love frome me

P

**Comment by jeffposnick** [comment]
After thinking about this some more, I'm of the opinion that this should be addressed via a new https://chromestatus.com/samples landing page, and we should create a top-level `index.html` in this repo that just contains a `<meta>` redirect there.

This repo is great for hosting new samples and offers a lot of flexibility around directory structure, including supporting JS/CSS files, and using HTTPS. This repo is not ideal for storing metadata about what each sample relates to (Networking, Multimedia, ES6, etc.) and metadata about which version of Chrome it's associated with. While we could try to add that metadata to each sample in a way that would be parseable by an index-generator, we'd effectively be replicating what already exists in the chromestatus.com backend. Without that metadata, putting together a meaningful browsing/search experience seems like an uphill battle.

Using a hypothetical https://chromestatus.com/samples as the canonical samples list also means that samples that predate this repo or that, for whatever reason, aren't hosted in this repo will show up in the list.
