### ISSUE TITLE
index.html to open everytime even if i add to homescreen from other page.

### ISSUE THREAD

**Issue by kinup** [GoogleChrome/samples#377]
I have multiple pages like login page, aboutus page. When i go to about us page and do add to homescreen. On homescreen on clicking on icon it open about us page instead of index.html. how to i open index.html even though i add to homescreen from other page. Please help.

**Comment by kinup** [comment]
[html - Copy.zip](https://github.com/GoogleChrome/samples/files/334613/html.-.Copy.zip)

**Comment by jeffposnick** [comment]
Browsers that support the [web application manifest](https://github.com/GoogleChrome/samples/tree/gh-pages/web-application-manifest) will honor the [`start_url` field](https://github.com/GoogleChrome/samples/blob/gh-pages/web-application-manifest/manifest.json#L43) when launching from the homescreen. You can set that to `"index.html"`.

Browsers that don't support web application manifests will just return to whatever page the user was on when they manually added the site to their homescreen. You'd have to implement some sort of [client-side JavaScript check](http://stackoverflow.com/questions/10887676/can-the-url-for-the-add-to-home-screen-on-iphone-safari-be-customized) to detect those cases and redirect to the desired start page.
