### ISSUE TITLE
how do i cache images?

### ISSUE THREAD

**Issue by codymchane** [GoogleChrome/samples#378]
How do i cache images and other files (CSS, JS)?
Is this only for caching 1 HTML file?

**Comment by jeffposnick** [comment]
I'm assuming you're looking through the service worker examples. Many of them apply equally to HTML and other resources. E.g. https://github.com/GoogleChrome/samples/tree/gh-pages/service-worker/read-through-caching

If you have a concrete question or bug report about a given sample, please reopen this.
