### ISSUE TITLE
Service worker sample for single page static site

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/samples#391]
I always want the most basic sample for a service worker.

The workers for airhorner and mojibrush are good examples. They gotta do clients.claim() and skipWaiting(), toss files in the cache, and manage those. And that's it.

I'd love to have it here in this repo with the others.  
@addyosmani said he might look into it.

**Comment by addyosmani** [comment]
Started a thread with @jeffposnick about it, but in short: let's see if we can land a simpler sample :)

You were originally after something similar to what was landed in Lighthouse over [here](https://github.com/GoogleChrome/lighthouse/blob/7a1cad89ac9799a796f817602cc18ecf2724a4bb/lighthouse-cli/test/fixtures/offline-ready-sw.js), right?

**Comment by paulirish** [comment]
Yeah.

Airhorner has 1 single cache and the most simple single static page setup i can imagine:
https://github.com/GoogleChrome/airhorn/blob/master/app/sw.js

But if you want to 1) version your caches and 2) store dynamically fetched resources in the cache, then you'll end up here:
https://github.com/GoogleChrome/lighthouse/blob/7a1cad89ac9799a796f817602cc18ecf2724a4bb/lighthouse-cli/test/fixtures/offline-ready-sw.js

more or less.

**Comment by jeffposnick** [comment]
I can synthesize https://github.com/GoogleChrome/samples/tree/gh-pages/service-worker/prefetch and https://github.com/GoogleChrome/samples/tree/gh-pages/service-worker/read-through-caching, and leave out most of the comments.

@paulirish are you cool with this combined sample living in https://github.com/GoogleChrome/samples/tree/gh-pages/service-worker/basic, replacing the current content that you put together a couple of years ago?

**Comment by paulirish** [comment]
yup, happy for it to replace /basic.

basic is an interesting "fetch-handler-only" kind of example but since it isn't about offline i don't really consider it to be a "basic" example anymore.
