### ISSUE TITLE
Typo in Harmony classes demo

### ISSUE THREAD

**Issue by menixator** [GoogleChrome/samples#397]
[https://github.com/GoogleChrome/samples/blob/gh-pages/classes-es6/demo.js#L113](https://github.com/GoogleChrome/samples/blob/gh-pages/classes-es6/demo.js#L113)

**Comment by beaufortfrancois** [comment]
Thank you @menixator!
I'm uploading a PR to fix this at https://github.com/GoogleChrome/samples/pull/398
