### ISSUE TITLE
Use Web Starter Kit as the placeholder baseline.

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/samples#4]
At minimum I would suggest we go for the minimal options in https://github.com/google/web-starter-kit/blob/master/app/basic.html, if not the full layout options in https://github.com/google/web-starter-kit/blob/master/app/index.html.

basic.html support would just mean a few minor new additions atm. cc @PaulKinlan

**Comment by PaulKinlan** [comment]
A big +1 to this :+1:

**Comment by PaulKinlan** [comment]
It actually might seem stupid, but there are some things that I would like to see.  For example the Web StarterKit comment at the bottom.  We should be showing everyone that WSK is our base for all of our projects and it should be for theirs too.

**Comment by jeffposnick** [comment]
Sorry, yes, the samples did start out with the WSK templates and then I ended up paring away some structure. I probably went too far.

I'll do a sweep through and revise things a bit, with a PR for you folks to comment on prior to the M38 beta release.
