### ISSUE TITLE
Discover services sample fails at server.getPrimaryServices

### ISSUE THREAD

**Issue by heaversm** [GoogleChrome/samples#434]
I'm using the BLE simulator with the battery service, and attempting to run the "Discover Services" sample. It fails at line 20: `return server.getPrimaryServices();` stating

```
Argh! NotFoundError: No Services found in device.
```

Any idea how to get this working. I saw an issue filed [here](https://github.com/GoogleChrome/samples/issues/411) but this didn't seem to work, though I think it might be related, as the documentation for [getPrimaryServices](https://webbluetoothcg.github.io/web-bluetooth/#dom-bluetoothremotegattserver-getprimaryservices) states that:

```
If this.device.[[allowedServices]] is not "all", and service is present and not in this.device.[[allowedServices]], return a promise rejected with a SecurityError and abort these steps.
```

Any idea how to resolve this - I'd love to get an example working that searches for any available devices and their services. Thanks!

**Comment by beaufortfrancois** [comment]
@heaversm Just to be sure, you need to write `battery_service` in the field such as https://googlechrome.github.io/samples/web-bluetooth/discover-services-and-characteristics.html?optionalServices=battery_service

From there, you should see the Battery Service and its characteristics in the sample.
If not, it may be a bug in our implementation.

**Comment by beaufortfrancois** [comment]
For info, we are going to update our error message so that it's clear to developers what is going wrong: https://bugs.chromium.org/p/chromium/issues/detail?id=656458

FYI @g-ortuno

**Comment by heaversm** [comment]
Ah, so is `getPrimaryServices()` not a catchall to list available services on a device? Does such a thing exist? My hope was to be able to build something that could connect to a device via bluetooth, browse the list of available services, choose one, and get its characteristics. 

BTW - your example works fine when `battery_service` is input into the field.

**Comment by beaufortfrancois** [comment]
You're right `getPrimaryServices` will only give you access to services you've expressly asked for (the ones in `filters services` and `optionalServices`).

A `getAllPrimaryServices` doesn't exist. It is actually what makes Web Bluetooth different. In the future, browsers may warn users with something like _"This website wants to pair with "foo" and uses "Battery Service" and "Device Information Service"._ 

See https://medium.com/@jyasskin/the-web-bluetooth-security-model-666b4e7eed2#.f2ms1h3d0 for more.

**Comment by heaversm** [comment]
Thanks,  you've been really helpful!

**Comment by beaufortfrancois** [comment]
No problem.
For info, I'm about to add a specific error for you (and other developers I'm sure) at https://codereview.chromium.org/2459523002/
