### ISSUE TITLE
Missing comment on Google Developers Web Updates

### ISSUE THREAD

**Issue by simevidas** [GoogleChrome/samples#438]
I apologize for posting this here, but I wasn’t able to find the repository for the Web Updates blog, and this seemed like the canonical Chrome team repo 😅. Could you please point me in the right direction?

The issue itself is that I’ve posted a comment to [this post](https://developers.google.com/web/updates/2016/10/css-hyphens) yesterday, but it doesn’t appear in the comments box. My comment is available [on Google+](https://plus.google.com/+%C5%A0imeVidas/posts/gMhxAnxQQjh) (because I have “Also share on Google+” enabled). Is this a known issue?

**Comment by addyosmani** [comment]
I believe you might be looking for https://github.com/google/WebFundamentals/

**Comment by simevidas** [comment]
That’s it; thanks!

Btw, there already seems to be [an issue for this](https://github.com/google/WebFundamentals/issues/3754).
