### ISSUE TITLE
Should https://github.com/GoogleChrome/samples/blob/gh-pages/service-worker/selective-caching/index.html switch to using a `manifest.json`?

### ISSUE THREAD

**Issue by mohawk2** [GoogleChrome/samples#441]
If so I'll be pleased to PR that!

**Comment by jeffposnick** [comment]
No, I don't believe so. The general philosophy has been to keep the individual samples in this repo focused on a single topic.

The samples under `service-worker/` each show off a specific type of behavior that a service worker might implement, without trying to behave like a full progressive web app.

There's a separate sample showing how and why a web app manifest might be used, at https://github.com/GoogleChrome/samples/tree/gh-pages/web-application-manifest
