### ISSUE TITLE
Remove icon density

### ISSUE THREAD

**Issue by miksh7** [GoogleChrome/samples#453]
The icon density seem to be not a part of the web manifest standard. Should it be removed from [manifest.json](https://github.com/GoogleChrome/samples/blob/gh-pages/web-application-manifest/manifest.json)?
Otherwise please explain its purpose.

**Comment by beaufortfrancois** [comment]
You're absolutely right. Here's a PR to fix it: https://github.com/GoogleChrome/samples/pull/457
