### ISSUE TITLE
How to disable auto suggest from browser

### ISSUE THREAD

**Issue by ahirhasmukh** [GoogleChrome/samples#484]
Please check below Image I have some issue on my browser when I am selecting city. this moment I don't need to browser suggestions so how can I disable to auto suggestion. you can provide me code so It is better for me

![autosuggestions](https://cloud.githubusercontent.com/assets/8941195/23200009/e531ff4c-f8f7-11e6-8463-148937a734b3.png)

**Comment by madmath** [comment]
Hi, discussions are better had on crbug.com/new. For your case, add autocomplete="off" to this field

<input type="text" ... autocomplete="off">

This issue can be closed.

**Comment by ahirhasmukh** [comment]
@madmath Thank you
