### ISSUE TITLE
Should application manifest be working on Chrome on desktop? 

### ISSUE THREAD

**Issue by stefek99** [GoogleChrome/samples#488]
- https://github.com/GoogleChrome/samples/tree/gh-pages/web-application-manifest
- https://googlechrome.github.io/samples/web-application-manifest/index.html

<img width="769" alt="screen shot 2017-03-05 at 11 39 55" src="https://cloud.githubusercontent.com/assets/249703/23586944/d5ba26bc-0198-11e7-8898-3f7fb7e514cd.png">

I think (correct if I'm wrong) that it is not working due to: http://stackoverflow.com/questions/12476210/cant-get-html5-appcache-working-correctly

```
.htaccess
AddType text/cache-manifest .appcache
```

https://mykmelez.github.io/offline-web-apps-on-github-pages/
> GitHub Pages would be a great place to host Offline Web Apps, if there was a way for them to ensure they'll be cached despite not having control over the web server configuration. Service Workers provides that missing piece. 

____

So in my understanding - no offline due to lack of server configuration. To get it working offline on Github pages Service Workers required?

**Comment by beaufortfrancois** [comment]
Yes, we would need a Service Worker to make https://googlechrome.github.io/samples/web-application-manifest/index.html work offline. The Web Application manifest sample is just there to demonstrate the "Add to Home Screen" flow triggered by user.

This works as intended.
Look at https://github.com/GoogleChrome/samples/tree/gh-pages/service-worker for service worker related samples.

**Comment by stefek99** [comment]
OK, got it. It's not about working offline on desktop. It's about launching as app on Andoid:

```
  "start_url": "index.html",
  "display": "standalone",
  "orientation": "landscape"
```
