### ISSUE TITLE
Cache video sample crashes Chrome tab

### ISSUE THREAD

**Issue by martinvyro** [GoogleChrome/samples#506]
Hi,

the following demo crashes the Chrome tab:
https://github.com/googlechrome/samples/tree/gh-pages/service-worker/prefetch-video
(Actuall demo here: https://googlechrome.github.io/samples/service-worker/prefetch-video/index.html)

On the first-time page load it works, but on consequent loads - when the video is served by ServiceWorker - it crashes the tab either right away or after couple of clicks on the timeline and seeking to various (mostly un-buffered) points. It's not very consistent, sometimes it happens after every load, sometimes it needs a lot of clicking around and even multiple page loads.

Project of my own has a same problem, but it's not as consistent as this sample. It seems to be related to video size, the bigger the video, the more crashes.
I've tried to run Chrome using the `--enable-logging` flag and it seems that the bug is somehow related to video buffering, but it's hard to tell. Anyway, the log is attached and also the `net-internals` log.

It happens bot on Chrome 57.0.2987.133 (64-bit) and Chrome Canary 59.0.3057.0, running on Windows 10 Pro.

[logs.zip](https://github.com/GoogleChrome/samples/files/885881/logs.zip)

Not sure if this is the best place to report it, maybe it should be moved somewhere "closer" to the Chrome developers?

**Update:** it also happens on Mac OS.
**Update 2:** It seems that with videos, which are really short (<20s) it never happens.

**Comment by jeffposnick** [comment]
Looping in @samdutton, as it's his sample.

**Comment by samdutton** [comment]
+ Jake, Mounir and Paul L FYI.

**Comment by martinvyro** [comment]
@jeffposnick @samdutton can you reproduce the crash?

**Comment by concreted** [comment]
I'm also seeing this issue on OSX 10.12.4 with Chrome Version 58.0.3029.81 (64-bit).

**Comment by beaufortfrancois** [comment]
I can reproduce bug. Thank you!
I've filed it at https://bugs.chromium.org/p/chromium/issues/detail?id=716364
Please follow updates over there
