### ISSUE TITLE
Offline-Analytics demo does not work in Firefox

### ISSUE THREAD

**Issue by steveworkman** [GoogleChrome/samples#507]
When replaying the analytics request in Firefox, the object store is opened but the cursor is never returned due to a TransactionInactiveError. This does not happen in Chrome.

It may be better to re-write this code with IndexedDB 2 syntax and promises as the whole code isn't very testable with lots of global variables that aren't reset between tests. I've had a go at doing this for myself, and the gist of that is here: https://gist.github.com/steveworkman/90936242b21c7b85a43525fd911c1242

**Comment by gauntface** [comment]
@steveworkman Moved this over to the sw-helpers repo. Closing this one and will comment on the other issue :)
