### ISSUE TITLE
Foreign-fetch not working

### ISSUE THREAD

**Issue by tiagojdf** [GoogleChrome/samples#512]
I have recently started reading about the foreign-fetch service worker API and this is one of the most prominent search results from google. 

I have tried your example and it doesn't seem to work. I have also read in the docs that the trial has finished in March, but I can't seem to find any follow up information regarding this topic, so I am not sure how I can implement service workers across several subdomains.

It would be great if you could update this demo and update the documentation to reflect recent changes.

**Comment by caraya** [comment]
If this was an origin trial and there is no more information you may want to contact the people listed in the [chromestatus entry](https://www.chromestatus.com/features/5684130679357440) because unless they launch a new origin trial there is no real way to implement this.
