### ISSUE TITLE
Media error message sample doesn't show an error message for 2 of the 4 buttons

### ISSUE THREAD

**Issue by wolenetz** [GoogleChrome/samples#528]
Trying the example at https://googlechrome.github.io/samples/media/error-message.html , it looks like two of the four buttons don't result in error : Non existent file, and Invalid file

But when I tried similar steps on the same browser to elicit errors and error messages, I could see the desired error messages. So I think something on the example page might be broken for those two buttons.

I'll add manual steps in a subsequent post on this issue.

**Comment by wolenetz** [comment]
Steps to see that the scenarios behind those two buttons should indeed emit error messages:
1) browse to https://storage.googleapis.com/media-error/no_streams.webm
2) observe in devtools console that $('video').error is null (strange, but maybe this can illuminate why the example page also sees no error).
3) on that same page's devtools, enter and observe the following, demonstrating that at least from devtools context the errors can be produced:
var v = $('video')
--> undefined
v
--> <video controls autoplay name=​"media">​…​</video>​
v.addEventListener('error', function() { console.log('ERROR'); });
--> undefined
v.src='';
--> "" VM206:1
--> ERROR
v.error
--> MediaError {code: 4, message: "MEDIA_ELEMENT_ERROR: Empty src attribute"}
v.src='https://storage.googleapis.com/media-error/no_streams.webm'
--> "https://storage.googleapis.com/media-error/no_streams.webm" VM206:1
--> ERROR
v.error
--> MediaError {code: 4, message: "DEMUXER_ERROR_COULD_NOT_OPEN: FFmpegDemuxer: open context failed"}
v.src='invalidfile.webm'
--> "invalidfile.webm" invalidfile.webm:1 GET https://storage.googleapis.com/media-error/invalidfile.webm 403 () VM206:1
--> ERROR
v.error
--> MediaError {code: 4, message: "MEDIA_ELEMENT_ERROR: Format error"}

**Comment by beaufortfrancois** [comment]
I can't reproduce sadly. It works great for me in Chrome 62.0.3164.0 (Official Build) canary (64-bit). Which Chrome version and platform do you use?

![screenshot 2017-07-25 at 6 48 34 am](https://user-images.githubusercontent.com/634478/28556289-8a2fd480-7105-11e7-994a-395b4c0b1e4e.png)

**Comment by wolenetz** [comment]
I only repro this when not in Incognito. Examining my extensions, I found one that rewrites some URLs, and is disabled in Incognito mode. Therefore, I think this is not an issue with your page; rather an issue if such an extension is in use.
