### ISSUE TITLE
Add more referrer policies?

### ISSUE THREAD

**Issue by domfarolino** [GoogleChrome/samples#548]
I noticed that in https://github.com/GoogleChrome/samples/blob/gh-pages/fetch-api/fetch-referrer-policy.js we only have 5 referrer policies that we're testing. Is there a reason we don't have all of them? Perhaps the demo was created before all of the policies were finalized? I'd be happy to submit a PR.

Reference: https://w3c.github.io/webappsec-referrer-policy/#referrer-policies

**Comment by domfarolino** [comment]
Bumping this thread. @jeffposnick thoughts?

**Comment by jeffposnick** [comment]
My recollection is that those were the supported ones when I put together the demo. Feel free to PR in additional ones, and CC: me on the review!
