### ISSUE TITLE
we can construct Response with string.

### ISSUE THREAD

**Issue by Jxck** [GoogleChrome/samples#63]
https://github.com/GoogleChrome/samples/blob/gh-pages/service-worker/mock-responses/service-worker.js#L31

first argument of `Response` constructor is a `BodyInit` and, this defined like this.

```
typedef (Blob or BufferSource or FormData or URLSearchParams or USVString) BodyInit;
```

so we can send JSON.stringify ed string of object without wrapping Blob.
at least, chrome canary 42 works fine with it.

**Comment by jeffposnick** [comment]
You're correct—the `Blob` requirement was dropped from the spec, and I confirmed that Chrome 40+ supports using a string. I'll adjust the sample.
