### ISSUE TITLE
Web Bluetooth does not evaluate characteristic properties from nRF51

### ISSUE THREAD

**Issue by PaulDFoster** [GoogleChrome/samples#655]
I have a Health Thermometer service implemented with an Adafruit 32u4 Bluefruit, using the latest available firmware.
If I review this service in the Android Nordic Semiconductor Connect app I can see the service properties I have set.
If I use the Web Bluetooth characteristics sample (https://googlechrome.github.io/samples/web-bluetooth/characteristic-properties.html?service=health_thermometer&characteristic=temperature_measurement) it does not evaluate the service characteristics. I see only Indicate set to true, even after I make modifications to the service properties on the device - such as enabling READ, or/and NOTIFY. The Android app shows the service properties correctly.

Sample output:
Requesting Bluetooth Device...
Connecting to GATT Server...
Getting Service...
Getting Characteristic...
> Characteristic UUID:  00002a1c-0000-1000-8000-00805f9b34fb
> Broadcast:            false
> Read:                 false
> Write w/o response:   false
> Write:                false
> Notify:               false
> Indicate:             true
> Signed Write:         false
> Queued Write:         false
> Writable Auxiliaries: false

**Comment by beaufortfrancois** [comment]
Can you share a screenshot of the Android Nordic Semiconductor Connect app to compare?

**Comment by PaulDFoster** [comment]
In this screen shot you can see the health thermometer service temperature measurement is seen with Indicate, Notify and Read in the nRF Connect app. While Web Bluetooth gives the same results as in my original post.

![Screenshot_20191021-183718_nRF Connect](https://user-images.githubusercontent.com/15899022/67228955-38ccd180-f432-11e9-8640-f778d532f718.jpg)

**Comment by PaulDFoster** [comment]
I should add that I'm running Web Bluetooth in Chrome on Windows 10.
Chrome: Version 77.0.3865.120 (Official Build) (64-bit)
Windows 10: 10.0.18362
The Adafruit 32u4 BlueFruit Software revision is 0.8.1 - Apr 10, 2019, firmware version S110 8.0.0,0.2, hardware revision: QFACA00

**Comment by beaufortfrancois** [comment]
Can you reproduce on Android from https://googlechrome.github.io/samples/web-bluetooth/characteristic-properties.html?service=health_thermometer&characteristic=temperature_measurement
I wonder if Web Bluetooth on Windows behaves differently.

**Comment by PaulDFoster** [comment]
Sorry Francois, I should have just done that.

Yes it works correctly on Android.

Many thanks
Paul

**Comment by PaulDFoster** [comment]
Awaiting confirmation of Windows Bluetooth stack issue.

**Comment by beaufortfrancois** [comment]
For info, you may want to check `chrome://bluetooth-internals` as well

**Comment by PaulDFoster** [comment]
Windows 10 build 18362 does not surface service characteristics correctly in Chrome using Web Bluetooth. I will report back more information once I have determined the exact reasons.
