### ISSUE TITLE
MediaError.message Sample's invalid file case is cross-origin; message is cleared as a result

### ISSUE THREAD

**Issue by wolenetz** [GoogleChrome/samples#664]
In M68, Chromium included a change (https://chromium-review.googlesource.com/c/chromium/src/+/1015794/) that clears the error message before exposing it to JS via a MediaError, in the case where the media "should be opaque". This opacity condition is satisfied by the Sample (because no_streams.webm is cross-origin), so that case now just emits an error with an empty message.

This issue tracks updating the sample in one or both of the following ways:

1. Explicitly note that the cross-origin no_streams.webm / invalid file case is not expected to produce an error message.
2. Include an invalid file case where the resource is not cross-origin, and the error message is still populated and exposed in current Chrome.

@beaufortfrancois - please triage and let me know if you have any questions.
See also https://crbug.com/1012728 where this Sample's change in behavior around the invalid file case was reported.

**Comment by beaufortfrancois** [comment]
@wolenetz Thanks for catching this issue.

If https://github.com/GoogleChrome/samples/pull/665 looks good you, I'll merge and close this issue.

**Comment by wolenetz** [comment]
#665 LGTM. Thank you.

**Comment by beaufortfrancois** [comment]
https://googlechrome.github.io/samples/media/error-message.html is now live with changes.
