### ISSUE TITLE
Issue when Writing NDEF to NFC Tag

### ISSUE THREAD

**Issue by OlivierGrenoble** [GoogleChrome/samples#680]
I'm using the WebNFC API. I have a problem with the write function. It works but Android immediately reads the NDEF message that I have written and displays a popup.
I would like to disable this "read" when writing an NDEF message into the tag. How can I do it? I have tried to set ignoreRead to true but it doesn't help. 

```
writer.write("Hello World", { ignoreRead: true })
	.then(() => {
    console.log("Message written.");
  }).catch(error => {
    console.log(`Write failed :-( try again: ${error}.`);
  });
```

BTW, if I want to set several options, shall I separate them with a comma? Example:
`writer.write(message, { ignoreRead: true, signal: abortController.signal })`

For information, I have seen a small error on https://web.dev/nfc/
There is:
`await writer.push("Hello world", { signal: abortController.signal });`

I think that it should be writer.write()

**Comment by beaufortfrancois** [comment]
> I'm using the WebNFC API. I have a problem with the write function. It works but Android immediately reads the NDEF message that I have written and displays a popup.
> I would like to disable this "read" when writing an NDEF message into the tag. How can I do it? I have tried to set ignoreRead to true but it doesn't help.

You may want to run scan() and discard onreading events if your app is in a "write UI mode".
Note that `{ ignoreRead: true }` is already the default option.

```js
const reader = new NDEFReader();
await reader.scan();
reader.onreading = event => {
  if (shouldProcessReadingEvents) { /* ... */ }
};

var shouldProcessReadingEvents = false;
const writer = new NDEFWriter();
await writer.write("Hello World");
console.log("Message written.");
```

> BTW, if I want to set several options, shall I separate them with a comma? Example:
> `writer.write(message, { ignoreRead: true, signal: abortController.signal })`

Yep!

> For information, I have seen a small error on https://web.dev/nfc/
> There is:
> `await writer.push("Hello world", { signal: abortController.signal });`
> 
> I think that it should be writer.write()

Indeed. Thanks for catching this issue: https://github.com/GoogleChrome/web.dev/pull/2381/files

**Comment by OlivierGrenoble** [comment]
Thank you François

**Comment by OlivierGrenoble** [comment]
> You may want to run scan() and discard onreading events if your app is in a "write UI mode".

Isn't that a pity that it is not the default behavior? When writing to a tag, one seldom needs the processing by NFC service of the NDEF freshly written.

**Comment by beaufortfrancois** [comment]
Do you mind sharing this feedback to https://github.com/w3c/web-nfc/issues so that other web developers see this?
This repository is for the Web NFC sample, not the spec.

**Comment by OlivierGrenoble** [comment]
Ok I will

**Comment by OlivierGrenoble** [comment]
Here it is: https://github.com/w3c/web-nfc/issues/551

**Comment by beaufortfrancois** [comment]
Thanks!
