### ISSUE TITLE
NFC allows reading but does not return any data

### ISSUE THREAD

**Issue by andraz-at** [GoogleChrome/samples#682]
Both `err` and `event` contain the the same data: `{"isTrusted":true}`

```javascript
      const reader = new window.NDEFReader()

      reader
            .scan()
            .then(() => {
              window.alert('Scan started successfully.')

              reader.onerror = (err) => {
                window.alert('error: ' + JSON.stringify(err))
              }

              reader.onreading = (event) => {
                window.alert('read: ' + JSON.stringify(event))
              }
            })
            .catch((error) => {
              window.alert(`Error! Scan failed to start: ${error}.`)
            })
        }
```

What is the proper way to read NFC data in the latest Android build?

https://googlechrome.github.io/samples/web-nfc/ does not return any data after _Scan started_.

**Comment by andraz-at** [comment]
Ignore this, updating the browser to latest build fixed the issue. The linked example works ok.

**Comment by 121940kz** [comment]
> Ignore this, updating the browser to latest build fixed the issue. The linked example works ok.

I am having this same behavior and can't figure it out. I am updated on the most recent version and am still getting the isTrusted: true issue. Any other ideas to try?

**Comment by marius-oprea** [comment]
ndef.onreading = ({ message, serialNumber }) => {...}

Give it exactly those arguments as in the example above. It doesn't work with a single generic event arg.

If you remote debug your android chrome page on your PC and console.log(event), you will get all properties (message and serialNumber).
https://developer.chrome.com/docs/devtools/remote-debugging/

https://developer.mozilla.org/en-US/docs/Web/API/NDEFReadingEvent

**Comment by marius-oprea** [comment]
Actually if you console.log(event) on your PC, you will get a bunch of properties.
https://developer.chrome.com/docs/devtools/remote-debugging/
