### ISSUE TITLE
QuicTransport throws TypeError: Connection lost.

### ISSUE THREAD

**Issue by guest271314** [GoogleChrome/samples#700]
```
Initiating connection...
Connection ready.
Error while reading datagrams: TypeError: Connection lost.
Error while accepting streams: TypeError: Connection lost.
Connection closed abruptly.
Error while sending data: TypeError: Connection lost.
```

**Comment by guest271314** [comment]
Solved.

**Comment by Atul-Bari** [comment]
can u guide how its solved @guest271314

**Comment by guest271314** [comment]
@Atul-Bari There have been several changes since I filed this. The last time I checked the code in this repository did not work. I advised the authors of that https://github.com/GoogleChrome/samples/pull/733#issuecomment-933488424.
