### ISSUE TITLE
Is QuicTransport obsolete?

### ISSUE THREAD

**Issue by guest271314** [GoogleChrome/samples#711]
Is `QuicTransport` and obsolete per [QuicTransport => WebTransport OT #4208](https://github.com/GoogleChrome/web.dev/pull/4208)?

Should a webstransport directory be created housing [Examples](https://w3c.github.io/webtransport/#example-complete) from [WebTransport
Editor’s Draft, 11 November 2020](https://w3c.github.io/webtransport/#dictdef-streamabortinfo), and quicktransport directory be archived or deleted from samples?

**Comment by jeffposnick** [comment]
Now that Chrome 87 is fully rolled out, yes, the existing https://googlechrome.github.io/samples/quictransport/client.html needs to be rewritten to account for the WebTransport changes.

In the meantime, referring to the samples from the WebTransport Editor's Draft is the best course forward. I am hesitant to redeploy anything rewritten until the Editor's Draft has settled a bit, since otherwise we'll always need to catch up to the latest changes.

**Comment by guest271314** [comment]
@jeffposnick I rewrote my own `QuicTransport` experiments to use `WebTransport` though have not published them there, yet. 

Am relatively certain I do not have the authorization to create a webtransport directory here. I you create the directory I can substitute `WebTransport` code for `QuicTransport` code in the current quictransport directory, which then can be marked as archived.

 I noticed that web.dev is updated to reflect the PR's. I see no reason to not create the webtransport directory now since you verified that `QuicTransport` is obsolete. At least a Note can be included in the README.md to notify readers of samples of the state of the API.

**Comment by guest271314** [comment]
FWIW this is the repository that I updated and tested a few hundred times locally yesterday https://github.com/guest271314/quictransport.

**Comment by jeffposnick** [comment]
Thanks for volunteering that contribution, @guest271314!

If you fork this repo, you should be able to create a `webtransport` directory, and host your sample code there. Then, you could file a pull request against this repo's `gh-pages` branch, and assuming that's merged, your sample would be deployed.

(I'm personally not up on the latest WebTransport changes, so I might ask @vasilvv and @yutakahirano to help with the PR review.)
