### ISSUE TITLE
NDEF Reader is not defined

### ISSUE THREAD

**Issue by utkudenis** [GoogleChrome/samples#720]
Hi guys, 

I am trying to develop nfc card login page. 

web platform features enabled. ( also ı reset all settings and enable it again) 

My webpage is developing by using React and I'm reaching it(from tablet) by using localhost ip adress(my laptop adress) 

NFC read and write are working on other pages like https://kenchris.github.io/webnfc-groceries/ but it doesn't work in my code. 

That is the Code block 

![image](https://user-images.githubusercontent.com/68633376/116724492-64e2ee80-a9e9-11eb-8048-29e7f2b5080f.png)
 
Dou you have any suggestion ?

**Comment by beaufortfrancois** [comment]
I guess you should try using `http://localhost` instead of the IP as Web NFC is available only in httpS contexts (localhost is whitelisted, not the IP address).

**Comment by utkudenis** [comment]
@beaufortfrancois  Yes, i realized it, but ı think developers should add message like "You should use https connection or you need secure connection"... 
Now we are searching how we establish secure connection in localhost and ı have to reach it from tablet :(

**Comment by beaufortfrancois** [comment]
You can use `http://localhost` without secure connection. It should work.

**Comment by utkudenis** [comment]
> You can use `http://localhost` without secure connection. It should work.

WebNFC does not work :(

**Comment by beaufortfrancois** [comment]
It works great for me as you can see below. Can you share your results for those commands?
```js
window.location.href
window.NDEFReader
navigator.userAgent

```
![image](https://user-images.githubusercontent.com/634478/116868234-b3250700-ac0e-11eb-9bc1-66d27e7376ce.png)

**Comment by utkudenis** [comment]
Solution : https connection ( with or without trusted ssl does not matter)
