### ISSUE TITLE
Manufacturer data filter example throws exception when data prefix filter is used

### ISSUE THREAD

**Issue by gte1** [GoogleChrome/samples#721]
https://github.com/GoogleChrome/samples/blob/7374ed5d69cd9f4a40bd14b0c48bbb7819d96435/web-bluetooth/manufacturer-data-filter.js#L41

const in this type of for loop causes an exception. ref https://medium.com/@mautayro/es6-variable-declaration-for-loops-why-const-works-in-a-for-in-loop-but-not-in-a-normal-a200cc5467c2

Tried https://googlechrome.github.io/samples/web-bluetooth/manufacturer-data-filter.html?dataPrefix=08 on chrome canary 92.0.4499.0 and got "Uncaught TypeError: Assignment to constant variable. (Your browser may not support this feature.)"

@beaufortfrancois

**Comment by beaufortfrancois** [comment]
Thank you @gte1!

**Comment by gte1** [comment]
And thank you @beaufortfrancois for fixing this so fast !

**Comment by beaufortfrancois** [comment]
@gte1 See https://stackoverflow.com/questions/67020600/web-bluetooth-want-to-filter-on-manufacturer-data-when-using-navigator-bluetoot/67566056#67566056 ;)
