### ISSUE TITLE
WebTransport Error: 296, reason: No common ALPN protocols

### ISSUE THREAD

**Issue by 1-leo** [GoogleChrome/samples#723]
Hi, i am trying the webtransport sample unfortunately i get no connection => 
`Error: 296, reason: No common ALPN protocols, frame_type: 6`
I think it has something to do with tls... i am using a self signed certificate and the chrome flag `chrome://flags/#allow-insecure-localhost` 

Chrome: canary 92.0.4502.0
Python 3.9.2

**Comment by jeffposnick** [comment]
Hello @leo-lox!

If you don't mind, could you ask about this at https://groups.google.com/a/chromium.org/g/web-transport-dev? The engineering team that wrote the original demo, and who are most up to date on the latest changes to the implementation, should see it there.

**Comment by 1-leo** [comment]
thx
