### ISSUE TITLE
device-information-characteristics-async-await example returning

### ISSUE THREAD

**Issue by WikiWookie** [GoogleChrome/samples#731]
Using this example
`https://googlechrome.github.io/samples/web-bluetooth/device-information-characteristics-async-await.html`

I can get the Manufacturer Identifier for a bluetooth device, but after that I get 
`Argh! RangeError: Offset is outside the bounds of the DataView`
when trying to get the system id.  What exactly is going on when retrieving that data and how can I get the 
`Organizationally Unique Identifier`
for my particular device?

**Comment by beaufortfrancois** [comment]
Can you share your JS code?

**Comment by WikiWookie** [comment]
For my particular issue it seems the manufacturer did not implement the specs correctly, so code-wise the example seems to be working as intended.
