### ISSUE TITLE
How to get plain text from NDEF Record object?

### ISSUE THREAD

**Issue by XxCodoxX** [GoogleChrome/samples#732]
I use this example https://googlechrome.github.io/samples/web-nfc/
and I have a question about  how do I get plain text from "log(`> Records: (${message.records.length})`);" this code

**Comment by beaufortfrancois** [comment]
See https://web.dev/nfc/#read-and-write-a-text-record

```js
  const textDecoder = new TextDecoder(record.encoding);
  console.log(`Text: ${textDecoder.decode(record.data)} (${record.lang})`);
```
