### ISSUE TITLE
WebTransport server intermittent TypeError: Connection lost.

### ISSUE THREAD

**Issue by guest271314** [GoogleChrome/samples#735]
When running the `WebTransport` server 

```
TypeError: Connection lost.
```

is intermittently thrown.

**Comment by jeffposnick** [comment]
CC: @bashi to see if they have any insight to share.

**Comment by bashi** [comment]
Thank you for looping me in. I [asked](https://github.com/bashi/samples/commit/2ebf629a99e33ae2e71fde6893d0d73286279e3e#r54593073) the reporter to file a bug in crbug.com and they did. https://crbug.com/1237781

**Comment by jeffposnick** [comment]
Thanks for following up—I'll close this in favor of the discussion in https://bugs.chromium.org/p/chromium/issues/detail?id=1237781
