### ISSUE TITLE
WebTrasnport: Failed to establish a connection to https://localhost:4433/counter: net::ERR_METHOD_NOT_SUPPORTED.. Opening handshake failed.

### ISSUE THREAD

**Issue by guest271314** [GoogleChrome/samples#742]
```
Failed to establish a connection to https://localhost:4433/counter: net::ERR_METHOD_NOT_SUPPORTED.
client.html:1 Uncaught (in promise) WebTransportError: Opening handshake failed.
```

**Comment by guest271314** [comment]
@bashi WebTransport server at WPT is apparently being tested successfully. Can you folks kindly update webtransport_server.py in this repository so that 

```
Uncaught (in promise) WebTransportError: Opening handshake failed.
```
does not occur?

**Comment by jeffposnick** [comment]
Please see https://github.com/GoogleChrome/samples/pull/749

**Comment by guest271314** [comment]
@jeffposnick Handshake error is occurring again.

**Comment by aboba** [comment]
The [latest server code](https://github.com/GoogleChrome/samples/blob/gh-pages/webtransport/webtransport_server.py) seems to have fixed the issue.  However, client.js still has some (minor) problems.  I believe that a live working version is now hosted [here](https://webrtc.internaut.com/wt2/).

**Comment by aboba** [comment]
The problem seems to have re-emerged on Canary M98.  [This site](https://webrtc.internaut.com/wt2/) (running the python server + client.js) runs on Chrome M95, but not on Canary M98.0.4696.0

Error is: 
"Connection failed. WebTransportError: Opening handshake failed."

**Comment by aboba** [comment]
The latest python server PR seems to have fixed the issue.

**Comment by ZhiquanCao** [comment]
still same error 
`Initiating connection...
Connection failed. WebTransportError: Opening handshake failed.`

on my chrome
