### ISSUE TITLE
requestLEscan not working any more

### ISSUE THREAD

**Issue by arigus** [GoogleChrome/samples#776]
this demo not working on latest chrome. Looke like it closes automatically when press scan button, so no grant to scan.
Please, check and share how to fix it

**Comment by beaufortfrancois** [comment]
This issue is currently tracked at https://bugs.chromium.org/p/chromium/issues/detail?id=1323134.

**Comment by arigus** [comment]
So when would be fixed?


Sent from Yahoo Mail for iPhone


On Wednesday, June 29, 2022, 2:41 PM, François Beaufort ***@***.***> wrote:




This issue is currently tracked at https://bugs.chromium.org/p/chromium/issues/detail?id=1323134.

**Comment by beaufortfrancois** [comment]
There is no ETA yet. Your best bet is to follow progress in this bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1323134

**Comment by arigus** [comment]
Hi,Thanks for the prompt reply. Any workaround while waiting for the final fix?We used in smart school application for 2 years and need this function to work with.Thanks and Best Regards!Batulziiwww.sanchirtech.com
    On Wednesday, 29 June 2022 at 08:00:25 pm GMT+8, François Beaufort ***@***.***> wrote:  
 
 


There is no ETA yet. Your best bet is to follow progress in this bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1323134

**Comment by beaufortfrancois** [comment]
Noted. I've sent a message to the Chrome team at https://bugs.chromium.org/p/chromium/issues/detail?id=1323134#c12.

**Comment by beaufortfrancois** [comment]
For the record:

> The regression of this issue is caused by https://chromium-review.googlesource.com/c/chromium/src/+/2117052. This is confirmed by resetting the chromium repo back to that commit and the issue can be observed right after having that change.

> According to comment 27 (which links to an internal doc), we might want to evaluate a proper solution to address this issue. Current WIP CL https://chromium-review.googlesource.com/c/chromium/src/+/3752062 doesn't fix the issue in an appropriate way (ex: other kinds of bubble popping up might stop operations and cause more confusion). Besides, we can't just workaround it by ignoring focus change without proper security related checks, so we might want to take more time to evaluate a proper solution.

> But please rest assure this is in our priority list as this is a blocker for Issue 654897 and Issue 897312 which we are committed to work on in this Q3.

Source: https://bugs.chromium.org/p/chromium/issues/detail?id=1323134#c28

**Comment by arigus** [comment]
Hi, Any update?BR, Ulzii
    On Wednesday, 3 August 2022 at 02:58:07 pm GMT+8, François Beaufort ***@***.***> wrote:  
 
 


For the record:


The regression of this issue is caused by https://chromium-review.googlesource.com/c/chromium/src/+/2117052. This is confirmed by resetting the chromium repo back to that commit and the issue can be observed right after having that change.



According to comment 27 (which links to an internal doc), we might want to evaluate a proper solution to address this issue. Current WIP CL https://chromium-review.googlesource.com/c/chromium/src/+/3752062 doesn't fix the issue in an appropriate way (ex: other kinds of bubble popping up might stop operations and cause more confusion). Besides, we can't just workaround it by ignoring focus change without proper security related checks, so we might want to take more time to evaluate a proper solution.



But please rest assure this is in our priority list as this is a blocker for Issue 654897 and Issue 897312 which we are committed to work on in this Q3.


Source: https://bugs.chromium.org/p/chromium/issues/detail?id=1323134#c28
