### ISSUE TITLE
Question: Does the web bluetooth sample work on chrome android?

### ISSUE THREAD

**Issue by kpjf** [GoogleChrome/samples#783]
Forgive me if it's been asked and answered, but I can't seem to get it working... heart_rate/heart_rate_measurement... 

It'll connect to the device, but the `characteristic.startNotifications()` promise never resolves. Seems like the support should be there, am I missing a flag, or permission setting?

**Comment by beaufortfrancois** [comment]
Hello @kpjf!
- Can you reproduce with other platforms (desktop, mobile)? 
- Which Bluetooth device do you use?
- Can you share logs? See https://www.chromium.org/developers/how-tos/file-web-bluetooth-bugs/

**Comment by kpjf** [comment]
The demo, specifically [this demo](https://beaufortfrancois.github.io/samples/web-bluetooth/notifications.html), will work on desktop (Chrome 107) but fails on my android device (Pixel 7 Pro, Chrome 108)

I'm connecting to a Whoop strap. 

I'll try and get the logs from the phone.

Thank you for the reply... first time playing with the bluetooth API.

**Comment by kpjf** [comment]
Digging into the bluetooth-internals to see if there's a difference in the characteristic properties desktop to phone. 

On my desktop the characteristic has the read properties, but on my phone, it's only got notify. So there's that.

**Comment by beaufortfrancois** [comment]
Good to hear!
