### ISSUE TITLE
Chrome browser crashes when calling ndef.scan multiple times without browser refresh, affects single-page web app

### ISSUE THREAD

**Issue by ngaffer** [GoogleChrome/samples#795]
Chrome browser crashes when 'ndef.scan' is called immediately after physically scanning an NFC tag. If you physically scan an NFC tag, refresh the browser, and then call ndef.scan again, the browser will not crash. 

When I use the Angular Router to navigate within my single-page web app without refreshing the page, the browser crashes when I navigate away and then back to my route that has the component with the NDEFReader object and ndef.scan call.

```
const ndef = new NDEFReader();
await ndef.scan();
```

Full code: https://github.com/GoogleChrome/samples/blob/gh-pages/web-nfc/index.js

**Steps to reproduce**
1. Navigate to the official sample content [https://googlechrome.github.io/samples/web-nfc/](https://googlechrome.github.io/samples/web-nfc/)
2. Click the 'Scan' button
3. Scan an NFC tag
4. Now click the 'Scan' button again
5. Notice that the browser crashes

**Comment by beaufortfrancois** [comment]
I'll close this issue and will continue on https://bugs.chromium.org/p/chromium/issues/detail?id=1424208. Thank you!
