### ISSUE TITLE
Is `vibrate` supposed to work on Android emulator?

### ISSUE THREAD

**Issue by cmahnke** [GoogleChrome/samples#845]
Maybe it's also related due to the poor support for vibrate in the emulator in general:
```
./Library/Android/sdk/platform-tools/adb logcat -b system
```

BTW, someone needs to clean up this issue tracker.

**Comment by markafoltz** [comment]
If this is a feature request for the Android emulator, please file the issue with the maintainers of that emulator.   There isn't enough information here for me to tell which emulator you are referring to.
