### ISSUE TITLE
SW Sample: storing data

### ISSUE THREAD

**Issue by owencm** [GoogleChrome/samples#85]
I have a session token in my page that I want to use in my SW.

I'm using postMessage to send it to the SW and then plan on using IDB to store it there.

A small sample that stores bits of (non-response) data persistently would be pretty nice, imho.

**Comment by jeffposnick** [comment]
FWIW, https://github.com/GoogleChrome/samples/blob/gh-pages/service-worker/offline-analytics/service-worker.js shows off storing failed Google Analytics requests using `IndexedDB`.

We could put together a more generic sample if you think that's useful. I'd imagine the controlled page could just write directly to `IndexedDB` and the service worker could read from it instead of having to use `postMessage()`, though.

**Comment by owencm** [comment]
I think this is a common enough need that having a small sample for storing and reading data on both sides would be neat. I imagine most apps need it, especially if they - like me - need to do authenticated network requests with tokens both from the page and from the SW. 

Plus, trying to get up and running with IDB just to store one session token is a real annoyance right now.

**Comment by markafoltz** [comment]
@owencm Can you use localStorage if your page and service worker share the same scope (origin)?

Here is what Gemini comes up with:

```html
<!DOCTYPE html>
<html>
<head>
  <title>Token Storage Example</title>
</head>
<body>
  <h1>Token will be stored and accessed by Service Worker</h1>

  <script>
    // 1. Store the token in localStorage
    const myToken = "your_example_token_here"; // Replace with your actual token
    localStorage.setItem('myAppToken', myToken);
    console.log('Token stored in localStorage:', myToken);

    // 2. Register the Service Worker
    if ('serviceWorker' in navigator) {
      navigator.serviceWorker.register('/service-worker.js')
        .then(registration => {
          console.log('Service Worker registered with scope:', registration.scope);
        })
        .catch(error => {
          console.error('Service Worker registration failed:', error);
        });
    }
  </script>
</body>
</html>
```

`service-worker.js:`
```js
// service-worker.js

self.addEventListener('fetch', (event) => {
  // 1. Read the token from localStorage
  const storedToken = localStorage.getItem('myAppToken');

  // 2. Log or use the token
  console.log('Token retrieved in Service Worker:', storedToken);

  // Example: Add token to request headers (modify as needed)
  if (storedToken) {
    const modifiedHeaders = new Headers(event.request.headers);
    modifiedHeaders.append('Authorization', `Bearer ${storedToken}`); 

    const modifiedRequest = new Request(event.request, {
      headers: modifiedHeaders,
    });

    event.respondWith(
        fetch(modifiedRequest)
          .then(response => {
            return response;
          })
          .catch(error => {
            console.error("Fetch error in service worker:", error);
            throw error;
          })
      );
  } else {
      event.respondWith(
        fetch(event.request)
          .then(response => {
            return response;
          })
          .catch(error => {
            console.error("Fetch error in service worker:", error);
            throw error;
          })
      );
  }
});
```

If you think this is worth adding to the samples repo, feel free to send a PR.
