### ISSUE TITLE
media-hover-pointer sample

### ISSUE THREAD

**Issue by patrickhlauke** [GoogleChrome/samples#90]
in the demo https://googlechrome.github.io/samples/media-hover-pointer/ it reads

>  if a user is on a tablet with a connected a mouse, 'any-pointer' will be satisfied. If the mouse is then removed, the browser will report 'any-pointer' as none.

Maybe I'm misunderstanding the spec, but why would/should `any-pointer` be `none` once the mouse is removed? wouldn't the fact that the touchscreen interface is still present count as a pointer device?

**Comment by mathiasbynens** [comment]
CC @samthor

**Comment by patrickhlauke** [comment]
I would expect a touchscreen+mouse combo to return both `fine` and `coarse` for `any-pointer`, and then once the mouse disappears, just `coarse`.

so the sentence should probably be (if I understand the spec right):

> if a user is on a tablet with a connected mouse, 'any-pointer' will match both 'coarse' (for the touchscreen) and 'fine' (for the mouse). If the mouse is then removed, the browser will just match 'coarse'.

or similar...

**Comment by patrickhlauke** [comment]
ok, i've gone and actually tested this using my own little test page http://patrickhlauke.github.io/touch/pointer-hover-any-pointer-any-hover/

as i suspected, the sentence currently in the demo is wrong - a touchscreen device without a mouse will have `any-pointer:coarse`; adding a mouse will result in `any-pointer:fine` and `any-pointer:coarse` evaluating as true; once you remove the mouse, it will still go back of course to `any-pointer:coarse` (and NOT `any-pointer:none`, as written in the demo)

![pointer-mq-without-with-mouse](https://cloud.githubusercontent.com/assets/895831/6624069/dd4cbe8e-c8de-11e4-8328-afcf53c4b63e.png)

in addition, the demo's CSS is wrong for the sized button. currently the demo has

```
@media (any-pointer: none), (any-pointer: coarse) {
        .sized {
          font-size: 1.5em;
        }
      }
```

however, even when a mouse is connected, `any-pointer:coarse` is true (as, remember, per spec `any-pointer` and `any-hover` can respond to multiple values, if there are multiple inputs present...and in this case, there is both a coarse input - the touchscreen - and a fine input - the mouse)

![demo-button-mouse](https://cloud.githubusercontent.com/assets/895831/6624132/4192ffe8-c8df-11e4-9207-88691ec3b97a.png)

so really, the above should probably be [edit: oops, forgot the "not"]

```
@media not (any-pointer: fine) {
        .sized {
          font-size: 1.5em;
        }
      }
```

**Comment by patrickhlauke** [comment]
and last nit-pick: the demo has

```
 @media (any-hover: none) {
      .demo:active {
        background: #00c;
        color: white;
      }
    }
```

but even on (my, at least) touchscreen in chrome, `any-hover:none` never evaluates to true (as just the touchscreen seems to still report `any-hover:on-demand` as true...so not sure where the effect of the blue `:active` state can actually be seen in action (possibly on a computer without any mouse/trackpad/touchscreen ?)

**Comment by patrickhlauke** [comment]
Sorry, one further point: possibly worth noting in the sample that currently `any-pointer` and `any-hover` don't update dynamically https://code.google.com/p/chromium/issues/detail?id=442418 (so the "If the mouse is then removed..." sentence may need some qualification). See also https://www.youtube.com/watch?v=nAh80QI8vlI

**Comment by addyosmani** [comment]
@samthor PTAL when you get a chance

**Comment by samthor** [comment]
Interestingly enough, the [spec](http://www.w3.org/TR/2014/WD-mediaqueries-4-20140605/#descdef-pointer) actually says that touchscreens could report `any-hover: none`.

I've fixed and simplified the demo and am sending a PR. Thanks.

**Comment by jeffposnick** [comment]
@samthor: Can we close this issue following the changes in #95, or is there still something left to be addressed?

**Comment by patrickhlauke** [comment]
Apologies, just testing this again, it seems I messed up with the variable size "Click me" button. It seems for some reason

```
@media not (any-pointer: fine)
```

isn't correctly evaluated (I keep getting the small button, even when my phone has no mouse paired).
The following seems to work

```
@media not all and (any-pointer: fine)
```

(this is likely due to some of the limitations of MQ3's `not`)
Alternatively, it may be easier to flip the logic of that block around...start with large button, then make it smaller for fine pointers, i.e.

```
.sized {
    font-size: 2.0em;
 }
@media (any-pointer: fine) {
    .sized {
      font-size: 0.5em;
    }
}
```
