### ISSUE TITLE
prefetch example should return the promise from addAll()

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/samples#96]
event.waitUntil won't currently wait for all assets to attempt to cache.

Its a subtle issue, but essentially a large number or big assets may hit a condition where the SW is terminated in the background.

Returning the addAll promise should fix this:
https://github.com/GoogleChrome/samples/blob/8a2d2663d61d7d0a7540af3ea7e79f41b6d5bd91/service-worker/prefetch/service-worker.js#L50

**Comment by jeffposnick** [comment]
Thanks for pointing that out, @gauntface!
